### ISSUE TITLE
[Q] - Why does the "Parse"-method (that new's up Organisationnummer instance), throw exception instead of i.e. bool?

### ISSUE THREAD

**Issue by joelmandell** [organisationsnummer/csharp#20]
In an API project I am doing checks if query is valid Organisationsnummer. I wonder why the Parse()-method is throwing exception instead of using a bool for example? 

Now in the app, I am naively checking if query is length according to a valid Organisatiosnummer and in that case passes to Parse()-method. This improves performance from around 130ms to 60ms for the api calls.

If this seems to be something that you think could be refactored, I can do a PR.

*WAS UPDATE, Changed Valid() To Parse() in this description*

**Comment by Johannestegner** [comment]
Hi there!

Not fully sure what you are asking.
The `Valid` method _should_ return a boolean value.

If you are asking about why we construct a new object in the static `valid` function instead of running a few checks on it I would say that it's mainly to keep it simple. All rules that would have to be checked for it to be seen as a valid org number is done in the constructor.

Could you show an example on what you are doing so I could get a clearer picture of the issue?

**Comment by joelmandell** [comment]
Well I see I missed to provide with some information. Sorry. It returns bool as you say. I meant the Parse method, which throws if invalid. And that decreases performance.

**Comment by Johannestegner** [comment]
Ah okay, yes, the parse method throws an exception.

Returning a bool would not be possible, as the return value is intended to be a Organisationsnummer instance, it's basically just a factory method for the object. The reason we throw an exception instead of returning something like a null value is cause we can include a lot more information in the exception (why did it fail), although, we have not been too good with that in the package. And `exceptions` are a quite standard way of error handling.

The idea is that the exception message should tell the consumer _why_ the parse function failed, much like the `int.Parse` method.

I could imagine implementing a `TryParse` function (return bool, out orgnr object), and will take it up with the team and see what they think.

Could you possibly post a snippet of your optimization so I could check what you do to make it faster? Or is it just the `try/catch` part required for exception handling that actually messes up the speed of the function?

**Comment by joelmandell** [comment]
I think it is just the tr/catch part that messes up the speed. ATM I am just making sure that two conditions are valid. The first is that the query length is according to the length of Organisationsnummer, if so it will pass it as param to the Valid() method.

In most cases the user will provide an valid Organisationsnummer when the query is according to the correct length.

**Comment by Johannestegner** [comment]
I understand!

I will have to do some test cases on the speed of the various checks we do in the parse function. Try/Catch does ofcourse have a penalty, but I would not expect it to be that high, but seeing our first test in the Parse function is a regex match (rather than a simple length check), it could be a bit more heavy than it should be.

I would imagine that checking the length would be a possible first check to do (although, we aught to check the length for short, long and separated short and long to confirm to the specs) it would still likely be faster.

I'll take it up with the team and see what we find being the best way of solving it :)

**Comment by Johannestegner** [comment]
We have discussed the issue and will recommend each package maintainer to add a length check on the number as a first test. I would imagine that this will speed up execution quite a bit in your case.
Further, I'll add a tryparse function to the c# project, as that is quite standard in the c# world.

Will close this issue when it's done :)
