### ISSUE TITLE
[FEATURE] - Handle FirmaTypes as an Enum instead of string

### ISSUE THREAD

**Issue by AnderssonPeter** [organisationsnummer/csharp#47]
**Description**
This would be a breaking change, but it would be a better DX if FirmaTypes was of type Enum instead of string.

**Comment by Johannestegner** [comment]
I kind of agree that it would be nice. But as of right now, the other packages makes use of strings, and changing the C# version to use enum would break the "same api in all languages" principle.

I will take it up with the other maintainers and see how they feel.

**Comment by Johannestegner** [comment]
Sorry for not being more responsive on this issue. I have considered it again to see if I can figure out a good way to implement this (could probably even be done without breaking too much of the API by just adding a new property for it) and can't really see a good way to do it.

First of, the enum would probably have to either be transtlated to english, or use `å, ä, ö` in a lot of words (it would be really ugly).
This could probably be done, but due to the fact that multiple values are 'Övrigt', we got more issues in that.

I've considered returning the integer value instead, and allow using that as an ID with a lookup table, which I also find kinda bad (especially due to us using kind of custom values for the types).

So in the end, I can't really find a good way to implement this without it being either very ugly or kinda useless, so for now, I'll close this issue and revisit it in the future in case I figure out a good way.

Feel free to come with implementation ideas and I might reopen and implement it in the future!
